# Generated by Django 4.0.1 on 2022-03-30 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Financials', models.IntegerField(default=0)),
                ('Academics', models.CharField(max_length=200)),
                ('Special_Exams', models.CharField(max_length=200)),
                ('Accomodation', models.CharField(choices=[('M', 'Mekatilili'), ('B', 'Blocks'), ('W', 'Mwangeka'), ('S', 'Starehe')], max_length=1)),
            ],
        ),
    ]
