# Generated by Django 4.0.1 on 2022-03-30 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_alter_dashboard_academics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='Academics',
            field=models.CharField(choices=[('R', 'Register_Units'), ('P', 'Provisional_results'), ('T', 'Provisional_Transcript'), ('E', 'Exam_Card')], max_length=2),
        ),
    ]
